services:
  cvat_db:
    ports: []

  cvat_redis_inmem:
    ports: []

  cvat_redis_ondisk:
    ports: []

  cvat_opa:
    ports: []   # <- unpublish 8181

  cvat_server:
    image: cvat/server:local
    ports:
      - "8080:8080"
    environment:
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1"
      CSRF_TRUSTED_ORIGINS: "http://localhost:3000,http://127.0.0.1:3000"
