#!/usr/bin/env python3
"""
Train a YOLO detector on your dataset and export a TensorRT engine (optionally convert from CVAT YOLO 1.1).

Now includes:
  • Robust CVAT YOLO 1.1 → Ultralytics dataset converter
  • `--check-trt` to print installed TensorRT + CUDA info
  • Safe YAML writing for data.yaml (handles colons, unicode)
  • Engine export paths:
      - Ultralytics .engine export (simple)
      - ONNX → **Python TensorRT builder** (no `trtexec` required)
      - ONNX → trtexec (optional)
  • Batch profiles via flags: --min-batch/--opt-batch/--max-batch (default 1/64/256)
"""

import argparse
import json
import glob
import os
from pathlib import Path
import random
import shutil
import sys
import tempfile
import zipfile
from typing import List, Tuple
import subprocess

import yaml
import torch.multiprocessing as mp

IMG_EXTS = {".jpg", ".jpeg", ".png", ".bmp", ".tif", ".tiff", ".webp"}


# =========================
# CLI
# =========================

def parse_args():
    p = argparse.ArgumentParser(description="Convert (optional), train YOLO, export TensorRT or ONNX")

    # Optional CVAT conversion inputs
    g = p.add_mutually_exclusive_group()
    g.add_argument("--cvat-zip", help="Path to CVAT export zip (YOLO 1.1)")
    g.add_argument("--cvat-dir", help="Path to an already-extracted CVAT YOLO 1.1 folder")
    p.add_argument("--out-dataset", help="Where to write the converted dataset (Ultralytics layout)")
    p.add_argument("--val-ratio", type=float, default=0.2, help="Validation split ratio if CVAT export has no split")
    p.add_argument("--symlink", action="store_true", help="Symlink images/labels instead of copying during conversion")

    # Dataset / model for training
    p.add_argument("--data", help="Path to YOLO data.yaml (skip conversion)")
    p.add_argument("--model", default="yolov8s.pt", help="Base model checkpoint (e.g., yolov8s.pt, yolov11s.pt)")

    # Training hyperparams
    p.add_argument("--imgsz", type=int, default=1280, help="Training/inference image size (square)")
    p.add_argument("--epochs", type=int, default=100, help="Number of training epochs")
    p.add_argument("--batch", type=int, default=16, help="Batch size")
    p.add_argument("--device", default="0", help="Device string for Ultralytics (e.g., '0', '0,1', 'cpu')")
    p.add_argument("--workers", type=int, default=8, help="Dataloader workers")
    p.add_argument("--seed", type=int, default=42, help="Random seed")
    p.add_argument("--patience", type=int, default=50, help="Early-stopping patience")

    # Augmentation knobs tuned for small logos/faces
    p.add_argument("--mosaic", type=float, default=1.0)
    p.add_argument("--mixup", type=float, default=0.2)
    p.add_argument("--degrees", type=float, default=10)
    p.add_argument("--translate", type=float, default=0.1)
    p.add_argument("--scale", type=float, default=0.7)
    p.add_argument("--shear", type=float, default=2.0)
    p.add_argument("--perspective", type=float, default=0.0005)
    p.add_argument("--fliplr", type=float, default=0.0)
    p.add_argument("--flipud", type=float, default=0.0)
    p.add_argument("--erasing", type=float, default=0.4)

    # Project layout
    p.add_argument("--project", default="runs/detect", help="Project directory")
    p.add_argument("--name", default=None, help="Run name; default is auto-generated by Ultralytics")

    # Validation/inference thresholds
    p.add_argument("--conf", type=float, default=0.15, help="Confidence threshold for val/track later")
    p.add_argument("--iou", type=float, default=0.6, help="IoU threshold for NMS")

    # Export options
    p.add_argument("--trt-half", action="store_true", help="Export/Build FP16 engine (builder or trtexec)")
    p.add_argument("--trt-dynamic", action="store_true", help="Dynamic shapes for Ultralytics' internal TensorRT export")
    p.add_argument("--trt-workspace", type=int, default=4096, help="TensorRT workspace size in MB (builder/trtexec)")
    p.add_argument("--int8", action="store_true", help="INT8 (requires Q/DQ ONNX or calibrator; builder/trtexec)")
    p.add_argument("--onnx-only", action="store_true", help="Skip TensorRT and only export ONNX")

    # Engine build paths
    p.add_argument("--build-with-python-trt", action="store_true", help="Use Python TensorRT builder (no trtexec)")
    p.add_argument("--build-with-trtexec", action="store_true", help="After ONNX export, run trtexec to build engine")
    p.add_argument("--trtexec", default="trtexec", help="Path to trtexec binary (if using trtexec)")

    # Batch profile controls for builder/trtexec
    p.add_argument("--min-batch", type=int, default=1, help="TensorRT min batch profile")
    p.add_argument("--opt-batch", type=int, default=64, help="TensorRT opt batch profile")
    p.add_argument("--max-batch", type=int, default=128, help="TensorRT max batch profile")
    p.add_argument("--onnx-input", type=str, default="images", help="ONNX input tensor name for trtexec shapes")
    p.add_argument("--engine-out", type=str, default=None, help="Optional engine output path (otherwise auto)")

    # Utilities
    p.add_argument("--check-trt", action="store_true", help="Print installed TensorRT and CUDA versions then exit")
    p.add_argument("--progress-file", type=str, default=None, help="Path to a JSON file where progress [0..1] is written")

    return p.parse_args()


# =========================
# CVAT → Ultralytics converter
# =========================

def _extract_zip(zip_path: Path) -> Path:
    tmp = Path(tempfile.mkdtemp(prefix="cvat_yolo11_"))
    with zipfile.ZipFile(zip_path, 'r') as z:
        z.extractall(tmp)
    return tmp


def _read_class_names(cvat_root: Path) -> List[str]:
    for name_file in ("obj.names", "classes.txt", "class.names", "obj.names.txt"):
        p = cvat_root / name_file
        if p.exists():
            names = [ln.strip() for ln in p.read_text(encoding="utf-8").splitlines() if ln.strip()]
            if names:
                return names
    return ["object"]


def _gather_pairs(cvat_root: Path) -> List[Tuple[Path, Path]]:
    pairs = []
    for img in cvat_root.rglob("*"):
        if img.suffix.lower() in IMG_EXTS and img.is_file():
            lbl = img.with_suffix('.txt')
            if lbl.exists():
                pairs.append((img, lbl))
    return pairs


def _split_pairs(pairs: List[Tuple[Path, Path]], val_ratio: float, seed: int) -> Tuple[List, List]:
    random.Random(seed).shuffle(pairs)
    n_val = int(len(pairs) * val_ratio)
    val = pairs[:n_val]
    train = pairs[n_val:]
    return train, val


def _safe_link_or_copy(src: Path, dst: Path, symlink: bool):
    dst.parent.mkdir(parents=True, exist_ok=True)
    try:
        if symlink:
            if dst.exists() or dst.is_symlink():
                dst.unlink()
            os.symlink(src, dst)
        else:
            shutil.copy2(src, dst)
    except OSError:
        shutil.copy2(src, dst)


def convert_cvat_yolo11(cvat_zip: Path | None, cvat_dir: Path | None, out_dataset: Path, val_ratio: float, symlink: bool, seed: int) -> Path:
    """Convert CVAT YOLO 1.1 export to Ultralytics dataset structure. Returns path to data.yaml."""
    if cvat_zip:
        tmp_root = _extract_zip(cvat_zip)
        cvat_root = tmp_root
    else:
        cvat_root = Path(cvat_dir)
        tmp_root = None

    # Guess actual data root (some exports nest a folder)
    candidates = [cvat_root]
    for sub in cvat_root.iterdir():
        if sub.is_dir():
            candidates.append(sub)
    def count_imgs(p: Path):
        return sum(1 for _ in p.rglob("*") if _.suffix.lower() in IMG_EXTS)
    cvat_data_root = max(candidates, key=count_imgs)

    names = _read_class_names(cvat_root)
    pairs = _gather_pairs(cvat_data_root)
    if not pairs:
        raise RuntimeError("No (image, label) pairs found in CVAT YOLO 1.1 export.")

    train_pairs, val_pairs = _split_pairs(pairs, val_ratio=val_ratio, seed=seed)

    # Write files
    for img, lbl in train_pairs:
        _safe_link_or_copy(img, out_dataset / "images" / "train" / img.name, symlink)
        _safe_link_or_copy(lbl, out_dataset / "labels" / "train" / lbl.name, symlink)
    for img, lbl in val_pairs:
        _safe_link_or_copy(img, out_dataset / "images" / "val" / img.name, symlink)
        _safe_link_or_copy(lbl, out_dataset / "labels" / "val" / lbl.name, symlink)

    # Write data.yaml safely
    data_yaml = out_dataset / "data.yaml"
    data_obj = {
        "path": str(out_dataset.resolve()),
        "train": "images/train",
        "val": "images/val",
        "names": [str(n) for n in names],
    }
    with open(data_yaml, "w", encoding="utf-8") as f:
        yaml.safe_dump(data_obj, f, sort_keys=False, allow_unicode=True)

    if tmp_root and tmp_root.exists():
        shutil.rmtree(tmp_root, ignore_errors=True)

    return data_yaml


# =========================
# Utilities
# =========================

def find_latest_best_weight() -> Path:
    candidates = glob.glob("runs/detect/**/weights/best.pt", recursive=True)
    if not candidates:
        raise FileNotFoundError("No best.pt found under runs/detect/**/weights. Did training complete?")
    latest = max(candidates, key=os.path.getmtime)
    return Path(latest)


def check_trt():
    try:
        import tensorrt as trt  # noqa: F401
        import cuda  # type: ignore  # may not exist; ignore
        ver = getattr(trt, "__version__", "?")
        cuda_ver = getattr(trt, "__cuda_version__", "?")
        print(f"[TRT] TensorRT __version__: {ver}")
        print(f"[TRT] Built against CUDA: {cuda_ver}")
    except Exception as e:
        print("[TRT] TensorRT not importable in this environment:", e)


# =========================
# Build engines
# =========================

def _normalize_names(names):
    """Normalize Ultralytics names into a list of strings sorted by class index."""
    if isinstance(names, dict):
        try:
            items = sorted(((int(k), v) for k, v in names.items()), key=lambda x: x[0])
        except Exception:
            # keys might already be ints
            items = sorted(names.items(), key=lambda x: int(x[0]))
        return [str(v) for _, v in items]
    if isinstance(names, list):
        return [str(x) for x in names]
    return None

def write_engine_metadata_sidecar(engine_path: Path, names, imgsz: int):
    """Write a YAML sidecar with minimal metadata so Ultralytics can map class ids to names."""
    names_list = _normalize_names(names)
    if not names_list:
        return
    meta = {
        "task": "detect",
        "imgsz": int(imgsz),
        "nc": len(names_list),
        "names": names_list,
    }
    sidecar = Path(engine_path).with_suffix(".yaml")
    try:
        with open(sidecar, "w", encoding="utf-8") as f:
            yaml.safe_dump(meta, f, sort_keys=False, allow_unicode=True)
        print(f"[INFO] Wrote engine metadata sidecar: {sidecar}")
    except Exception as e:
        print(f"[WARN] Failed to write engine metadata sidecar: {e}")

def build_engine_with_trtexec(onnx_path: Path, trtexec: str, imgsz: int, workspace: int, half: bool,
                              min_b: int, opt_b: int, max_b: int, onnx_input: str, engine_out: str | None):
    H = W = imgsz
    shape_flag = (
        f" --minShapes={onnx_input}:{min_b}x3x{H}x{W}"
        f" --optShapes={onnx_input}:{opt_b}x3x{H}x{W}"
        f" --maxShapes={onnx_input}:{max_b}x3x{H}x{W}"
    )
    precision = " --fp16" if half else ""
    onnx_p = Path(onnx_path)
    out_path = engine_out or str(onnx_p.with_name(onnx_p.stem + f"_b{max_b}.engine"))
    cmd = (
        f"{trtexec} --onnx={onnx_path} --saveEngine={out_path}"
        f" --workspace={workspace}" + precision + shape_flag
    )
    print("[INFO] Building TensorRT engine with trtexec:\n" + cmd)
    # Optional: ensure trtexec is present
    import shutil as _sh
    if not _sh.which(trtexec):
        raise RuntimeError(f"trtexec not found at '{trtexec}'. Install 'libnvinfer-bin' or pass --trtexec /full/path")
    subprocess.run(cmd, shell=True, check=True)
    print(f"[SUCCESS] Built engine: {out_path}")
    return out_path


def build_engine_with_python_trt(onnx_path: Path, engine_out: str | None, imgsz: int,
                                 min_b: int, opt_b: int, max_b: int, workspace: int,
                                 fp16: bool, int8: bool):
    """Build a TensorRT engine in **Python** (no trtexec) with batch profiles."""
    import tensorrt as trt

    logger = trt.Logger(trt.Logger.INFO)
    EXPL = 1 << int(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH)

    H = W = imgsz
    onnx_bytes = Path(onnx_path).read_bytes()

    with trt.Builder(logger) as builder, \
         builder.create_network(EXPL) as network, \
         trt.OnnxParser(network, logger) as parser, \
         builder.create_builder_config() as config:

        #builder.max_batch_size = 1  # unused for explicit, but must be set pre-TRT 10
        config.set_memory_pool_limit(trt.MemoryPoolType.WORKSPACE, workspace * (1 << 20))

        print(f"[INFO] Parsing ONNX: {onnx_path}")
        if not parser.parse(onnx_bytes):
            for i in range(parser.num_errors):
                print("[ONNX] Parse error:", parser.get_error(i))
            raise RuntimeError("Failed to parse ONNX")

        input_tensor = network.get_input(0)
        in_name = input_tensor.name

        profile = builder.create_optimization_profile()
        min_shape = (min_b, 3, H, W)
        opt_shape = (opt_b, 3, H, W)
        max_shape = (max_b, 3, H, W)
        profile.set_shape(in_name, min_shape, opt_shape, max_shape)
        config.add_optimization_profile(profile)

        if fp16 and builder.platform_has_fast_fp16:
            config.set_flag(trt.BuilderFlag.FP16)
        if int8:
            # For real INT8 you need Q/DQ ONNX or a calibrator
            config.set_flag(trt.BuilderFlag.INT8)
            print("[WARN] INT8 set without calibrator: expecting Q/DQ ONNX or provide calibrator in code.")

        print(f"[INFO] Building engine with batch profile: min={min_shape}, opt={opt_shape}, max={max_shape}")
        engine = builder.build_engine(network, config)
        if engine is None:
            raise RuntimeError("Engine build failed")

        out_p = Path(engine_out) if engine_out else Path(onnx_path).with_name(Path(onnx_path).stem + f"_b{max_b}.engine")
        out_p.write_bytes(bytearray(engine.serialize()))
        print(f"[SUCCESS] Saved engine to: {out_p}")
        return str(out_p)


# =========================
# Export orchestrators
# =========================

def export_with_fallback(export_model, imgsz: int, dynamic: bool, half: bool, workspace: int, device: str, data_yaml_path: Path | None, trtexec: str):
    """Try Ultralytics TensorRT export first; if it fails, export ONNX and print a trtexec command."""
    try:
        print("[INFO] Exporting to TensorRT via Ultralytics…")
        export_path = export_model.export(
            format="engine",
            half=half,
            dynamic=dynamic,
            imgsz=imgsz,
            workspace=workspace,
            device=device,
            data=str(data_yaml_path) if data_yaml_path else None,
        )
        print(f"[SUCCESS] Exported TensorRT engine: {export_path}")
        return export_path
    except Exception as e:
        print("[WARN] Ultralytics TensorRT export failed. Falling back to ONNX…")
        print(e)

    # ONNX fallback
    onnx_path = export_model.export(format="onnx", imgsz=imgsz, dynamic=True)
    print(f"[SUCCESS] Exported ONNX: {onnx_path}")

    # Compose a trtexec command suggestion
    H = W = imgsz
    min_b, opt_b, max_b = 1, 4, 8
    shape_flag = (
        f" --minShapes=images:{min_b}x3x{H}x{W}"
        f" --optShapes=images:{opt_b}x3x{H}x{W}"
        f" --maxShapes=images:{max_b}x3x{H}x{W}"
    )
    cmd = (
        f"{trtexec} --onnx={onnx_path} --saveEngine={(Path(onnx_path).with_name(Path(onnx_path).stem + '.engine'))}"
        f" --workspace={workspace} --fp16" + shape_flag
    )
    print("[INFO] To build a TensorRT engine with your system's TRT, run:")
    print(cmd)
    return None


# =========================
# Main
# =========================

def main():
    try:
        from ultralytics import YOLO
    except Exception as e:
        print("[FATAL] Failed to import ultralytics. Did you 'pip install ultralytics'?", file=sys.stderr)
        raise

    args = parse_args()
    try:
        mp.set_sharing_strategy('file_system')
    except Exception:
        pass
    def write_progress(val: float, extra: dict | None = None):
        try:
            if not args.progress_file:
                return
            payload = {"progress": float(max(0.0, min(1.0, val)))}
            if extra:
                payload.update(extra)
            Path(args.progress_file).parent.mkdir(parents=True, exist_ok=True)
            with open(args.progress_file, "w", encoding="utf-8") as pf:
                json.dump(payload, pf)
        except Exception:
            pass

    if args.check_trt:
        check_trt()
        return

    # 0) Optional: convert CVAT YOLO 1.1 export
    data_yaml_path: Path | None = None
    if args.cvat_zip or args.cvat_dir:
        if not args.out_dataset:
            print("[FATAL] --out-dataset is required when converting CVAT export.", file=sys.stderr)
            sys.exit(2)
        cvat_zip = Path(args.cvat_zip) if args.cvat_zip else None
        cvat_dir = Path(args.cvat_dir) if args.cvat_dir else None
        out_dataset = Path(args.out_dataset)
        print("[INFO] Converting CVAT YOLO 1.1 export → Ultralytics layout…")
        data_yaml_path = convert_cvat_yolo11(
            cvat_zip=cvat_zip,
            cvat_dir=cvat_dir,
            out_dataset=out_dataset,
            val_ratio=args.val_ratio,
            symlink=args.symlink,
            seed=args.seed,
        )
        print(f"[INFO] Wrote dataset to: {out_dataset}")
        print(f"[INFO] Generated data.yaml: {data_yaml_path}")
        # Handler sets 10% after download; ensure we keep at least that
        write_progress(0.1, {"phase": "prepared"})

    # If user supplied --data, that overrides conversion
    if args.data:
        data_yaml_path = Path(args.data)

    if data_yaml_path is None:
        print("[FATAL] Provide either --data or --cvat-zip/--cvat-dir + --out-dataset", file=sys.stderr)
        sys.exit(2)

    # 1) Train
    print("[INFO] Starting training…")
    # Ensure Ultralytics uses mounted runs directory
    try:
        import os as _os
        _os.environ.setdefault("ULTRALYTICS_RUNS_DIR", str(Path(os.environ.get("TMPDIR", "/opt/nuclio/workdir/tmp")).parent / "runs"))
    except Exception:
        pass
    model = YOLO(args.model)

    # Try to hook per-epoch progress callbacks (Ultralytics v8 API)
    def _epoch_cb(trainer):
        try:
            current = int(getattr(trainer, "epoch", 0)) + 1
            total = int(getattr(trainer, "epochs", args.epochs) or args.epochs)
            total = max(1, total)
            per_epoch = 0.8 / float(total)
            completed = max(0, min(current, total))
            frac = 0.1 + per_epoch * completed
            write_progress(frac, {"phase": "training", "epoch": current, "epochs": total})
        except Exception:
            pass
    try:
        # register on both names for broader compatibility
        if hasattr(model, "add_callback"):
            model.add_callback("on_train_epoch_end", _epoch_cb)
            model.add_callback("on_fit_epoch_end", _epoch_cb)
    except Exception:
        pass

    try:
        _ = model.train(
            data=str(data_yaml_path),
            imgsz=args.imgsz,
            epochs=args.epochs,
            batch=args.batch,
            device=args.device,
            workers=args.workers,
            seed=args.seed,
            patience=args.patience,
            project=args.project,
            name=args.name,
            # Augmentations
            mosaic=args.mosaic,
            mixup=args.mixup,
            degrees=args.degrees,
            translate=args.translate,
            scale=args.scale,
            shear=args.shear,
            perspective=args.perspective,
            fliplr=args.fliplr,
            flipud=args.flipud,
            erasing=args.erasing,
            cos_lr=True,
            cache=False,
        )
    except Exception as ex:
        # Mark failed status and re-raise for handler to capture exit code
        write_progress(1.0, {"phase": "failed", "error": str(ex)})
        print(f"[FATAL] Training failed: {ex}", file=sys.stderr)
        raise

    # Mark conversion/export phase start at 90%
    write_progress(0.9, {"phase": "export"})

    # 2) Locate best checkpoint
    try:
        best_pt = find_latest_best_weight()
    except FileNotFoundError:
        best_pt = None
        if hasattr(model, "ckpt_path") and model.ckpt_path and Path(model.ckpt_path).exists():
            best_pt = Path(model.ckpt_path)
        if best_pt is None:
            raise

    print(f"[INFO] Using best weights: {best_pt}")

    # 3) Export → choose path
    export_model = YOLO(str(best_pt))

    # Always get an ONNX when using builder/trtexec; otherwise try direct .engine export
    if args.onnx_only:
        onnx_path = export_model.export(format="onnx", imgsz=args.imgsz, dynamic=True)
        print(f"[SUCCESS] Exported ONNX: {onnx_path}")
        print("[TIP] Build engine with Python TRT (--build-with-python-trt) or trtexec (--build-with-trtexec).")

    elif args.build_with_python_trt:
        onnx_path = export_model.export(format="onnx", imgsz=args.imgsz, dynamic=True)
        print(f"[SUCCESS] Exported ONNX: {onnx_path}")
        engine_path = build_engine_with_python_trt(
            onnx_path=Path(str(onnx_path)),
            engine_out=args.engine_out,
            imgsz=args.imgsz,
            min_b=args.min_batch,
            opt_b=args.opt_batch,
            max_b=args.max_batch,
            workspace=args.trt_workspace,
            fp16=args.trt_half,
            int8=args.int8,
        )
        # Write sidecar metadata next to engine
        try:
            names = getattr(export_model, "names", None)
            if names is None and hasattr(export_model, "model"):
                names = getattr(export_model.model, "names", None)
            if engine_path:
                write_engine_metadata_sidecar(Path(engine_path), names, imgsz=args.imgsz)
        except Exception as _e:
            print(f"[WARN] Could not write metadata sidecar: {_e}")

    elif args.build_with_trtexec:
        onnx_path = export_model.export(format="onnx", imgsz=args.imgsz, dynamic=True)
        print(f"[SUCCESS] Exported ONNX: {onnx_path}")
        try:
            engine_path = build_engine_with_trtexec(
                onnx_path=Path(str(onnx_path)),
                trtexec=args.trtexec,
                imgsz=args.imgsz,
                workspace=args.trt_workspace,
                half=args.trt_half,
                min_b=args.min_batch,
                opt_b=args.opt_batch,
                max_b=args.max_batch,
                onnx_input=args.onnx_input,
                engine_out=args.engine_out,
            )
            # Write sidecar metadata next to engine
            try:
                names = getattr(export_model, "names", None)
                if names is None and hasattr(export_model, "model"):
                    names = getattr(export_model.model, "names", None)
                if engine_path:
                    write_engine_metadata_sidecar(Path(engine_path), names, imgsz=args.imgsz)
            except Exception as _e:
                print(f"[WARN] Could not write metadata sidecar: {_e}")
        except subprocess.CalledProcessError as e:
            print("[ERROR] trtexec build failed:", e)
            print("[HINT] Ensure --onnx-input matches your ONNX input name (default 'images') and TRT/CUDA are compatible.")

    else:
        # Original behavior: try Ultralytics engine export, then fallback to ONNX + printed trtexec command
        export_path = export_with_fallback(
            export_model,
            imgsz=args.imgsz,
            dynamic=args.trt_dynamic,
            half=args.trt_half,
            workspace=args.trt_workspace,
            device=args.device,
            data_yaml_path=data_yaml_path,
            trtexec=args.trtexec,
        )
        # Write sidecar metadata next to engine if we have an engine path
        try:
            names = getattr(export_model, "names", None)
            if names is None and hasattr(export_model, "model"):
                names = getattr(export_model.model, "names", None)
            if export_path:
                # Ultralytics can return Path, list, or str; normalize
                if isinstance(export_path, (list, tuple)) and export_path:
                    engine_candidate = Path(str(export_path[0]))
                else:
                    engine_candidate = Path(str(export_path))
                if engine_candidate.suffix == ".engine":
                    write_engine_metadata_sidecar(engine_candidate, names, imgsz=args.imgsz)
        except Exception as _e:
            print(f"[WARN] Could not write metadata sidecar: {_e}")

    # Done
    write_progress(1.0, {"phase": "done"})

if __name__ == "__main__":
    main()
